# Specify the build configuration
[build]
output = "dist"

# Configuration for the development server
[serve]
port = 8082

# (Optional) Additional static assets can be copied similarly
[[copy]]
source = "images"
destination = "images"
